feat: clean snapshot is added automatically
AVGTechnologies/online_kitchen pull request #36
Opened 2021-07-22 10:40 UTC by ireznice

2021-07-26 06:39 UTC, petrSchreiber requested changes
Minor request to clarify function purpose

2021-07-26 06:39 UTC, petrSchreiber commented on lib/online_kitchen/labmanager4.rb
> +        wait_for_machine_released(config, request_id)
I would propose to rename the method `wait_for_machine_released` to `wait_for_request_completion`.

2021-07-26 06:39 UTC, petrSchreiber commented on lib/online_kitchen/workers/lab_manager_equip.rb
> +        rand(2..7).seconds,
Nice speedup, thanks!

2021-08-02 07:38 UTC, ireznice commented on lib/online_kitchen/workers/lab_manager_equip.rb
>          equip_arg.merge('started' => true)
this is one of the things you should have detected :)

2021-08-03 06:30 UTC, petrSchreiber approved these changes
Tested change, thank you very much. It will increase the usability immensely.

2021-08-03 11:13 UTC, merged